version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src:rw
      - ./db:/usr/src/app/db:rw
    #   - ./:/usr/src/app/:rw
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
    restart: unless-stopped